// Generated by CoffeeScript 1.6.3
(function() {
  var FizzBuzz, fizz_buzz, i, _i;

  FizzBuzz = (function() {
    function FizzBuzz() {
      var n, shout, speak;
      n = 0;
      speak = function() {
        n++;
        if (n % 3 === 0 && n % 5 === 0) {
          return "FizzBuzz";
        }
        if (n % 3 === 0) {
          return "Fizz";
        }
        if (n % 5 === 0) {
          return "Buzz";
        }
        return n.toString();
      };
      shout = function() {
        n++;
        if (n % 3 === 0 && n % 5 === 0) {
          return "FIZZBUZZ";
        }
        if (n % 3 === 0) {
          return "FIZZ";
        }
        if (n % 5 === 0) {
          return "BUZZ";
        }
        return n.toString();
      };
      return {
        speak: speak(),
        shout: shout()
      };
    }

    return FizzBuzz;

  })();

  fizz_buzz = new FizzBuzz();

  for (i = _i = 1; _i <= 16; i = ++_i) {
    console.log(fizz_buzz.speak());
  }

}).call(this);
