// Generated by CoffeeScript 1.6.3
(function() {
  var buzz, fizz, i, _i;

  for (i = _i = 1; _i <= 15; i = ++_i) {
    fizz = i % 3 === 0;
    buzz = i % 5 === 0;
    console.log(i);
    if (fizz && buzz) {
      console.log('fizzBuzz');
    }
    if (fizz) {
      console.log('fizz');
    }
    if (buzz) {
      console.log('buzz');
    }
  }

}).call(this);
